apiVersion: v1
kind: Service
metadata:
  name: private-registry-service
spec:
  clusterIP: 10.98.43.129 
  type: NodePort
  selector:
    app: private-registry
  ports:
  - protocol: TCP
    port: 10002
    nodePort: 30000
    targetPort: 5000
