apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry-deployment
  labels:
    app: private-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      labels:
        app: private-registry
    spec:
      containers:
      - name: private-registry
        image: registry:2.7
